apiVersion: v1
kind: ConfigMap
metadata:
  name: rdma-devices
  namespace: kube-system
data:
  config.json: |
    {
        "mode" : "sriov",
        "pfNetdevices": [ "enp97s0f0" , "enp97s0f1", "enp97s0f2", "enp97s0f3"]
    }
